package modelo;

/**
 *
 * @author Mateo
 */
import java.util.Random;

public class GeneradorDePalabras {

    //private final String lenguaje;
    private String[] palabras;

    public GeneradorDePalabras(String lenguaje) {
        if (lenguaje.equalsIgnoreCase("Inglés")) {
            String[] palabrasIngles = {"apple", "banana", "car", "dog", "elephant", "flower", "guitar", "house", "internet", "jazz",
                "key", "lion", "moon", "notebook", "orange", "pizza", "queen", "river", "sun", "tree",
                "umbrella", "violet", "window", "xylophone", "yellow", "zebra", "airplane", "butterfly", "cat", "dolphin",
                "ear", "fire", "globe", "hat", "island", "jungle", "kite", "lemon", "mountain", "nest",
                "ocean", "pencil", "quilt", "rabbit", "star", "train", "unicorn", "vase", "water", "xylophone",
                "yacht", "zeppelin", "arch", "bird", "carrot", "desk", "elephant", "fireplace", "guitar", "house",
                "igloo", "jacket", "kangaroo", "leopard", "monkey", "nut", "ostrich", "piano", "queen", "rose",
                "sailboat", "tiger", "umbrella", "violin", "whale", "xylophone", "yarn", "zebra", "ant", "bear",
                "camel", "dinosaur", "eagle", "fish", "gorilla", "hamster", "insect", "jellyfish", "koala", "lion",
                "mango", "ninja", "octopus", "penguin", "quail", "raccoon", "snake", "turtle", "unicorn", "vampire",
                "whale", "xylophone", "yak", "zebra", "alligator", "bat", "cat", "dog", "elephant", "frog",
                "giraffe", "hippo", "iguana", "jaguar", "kangaroo", "lion", "monkey", "newt", "owl", "panda",
                "quokka", "rhino", "snake", "tiger", "uakari", "vulture", "walrus", "xenopus", "yak", "zebra", "accommodate", "bureaucracy", "colleague", "dyslexia",
                "entrepreneur", "fluorescent", "graffiti", "hierarchy",
                "inoculate", "juxtaposition", "knapsack", "labyrinth",
                "mnemonic", "onomatopoeia", "parliament", "queue",
                "rhythm", "synchronize", "tchotchke", "unbelievable",
                "vulnerable", "weird", "xylophone", "yacht",
                "zealous", "abracadabra", "bamboozle", "cacophony",
                "daiquiri", "ephemeral", "fahrenheit", "galvanize",
                "haphazard", "incandescent", "jamboree", "kaleidoscope",
                "lackadaisical", "magnificent", "nonchalant", "onomatopoeic",
                "pizzazz", "quizzical", "rampant", "sassafras",
                "tchotchke", "ukulele", "vagabond", "whimsical",
                "xenophobia", "yippie", "zeppelin", "aardvark",
                "beekeeper", "cacophony", "diphthong", "euphemism",
                "fandango", "gobbledygook", "hullabaloo", "iconoclast",
                "jackalope", "kaleidoscope", "logorrhea", "mellifluous",
                "naphthalene", "onomatopoeia", "pneumonia", "quagmire",
                "rhubarb", "scrumptious", "triskaidekaphobia", "ululate",
                "vuvuzela", "whippersnapper", "xerarch", "yowza",
                "zymurgy", "amazing", "bewilder", "circumference",
                "delirious", "enthusiasm", "fantastic", "gratuitous",
                "hilarious", "inquisitive", "jubilant", "kangaroo",
                "ludicrous", "magnificent", "necessity", "obnoxious",
                "perpendicular", "quizzical", "ridiculous", "surreptitious",
                "triumphant", "unbelievable", "vivacious", "wonderful",
                "xylophone", "yearning", "zealous", "abstract", "benevolent", "consequence", "delicate",
                "eloquent", "formidable", "gracious", "hypothesis",
                "impartial", "judicious", "knowledge", "luminous",
                "meticulous", "nurture", "objective", "prevalent",
                "quench", "resilient", "sophisticated", "transparent",
                "ultimate", "vibrant", "wander", "zeal",
                "adequate", "brisk", "coherent", "diligent",
                "eclectic", "flourish", "genuine", "harmonious",
                "illuminate", "jovial", "keen", "lucid",
                "magnify", "nuance", "optimistic", "profound",
                "quaint", "rational", "serene", "tangible",
                "unify", "versatile", "witty", "zealous",
                "acumen", "bravery", "convey", "dexterity",
                "eloquence", "fortitude", "gratitude", "humble",
                "innovative", "judgment", "kindness", "lively",
                "modest", "noteworthy", "optimism", "passionate",
                "quizzical", "reliable", "sincere", "tenacious",
                "unison", "vivid", "wondrous", "youthful",
                "zest", "affable", "bliss", "composure",
                "diligence", "effervescent", "flexible", "gentle",
                "honesty", "insightful", "joyful", "knowledgeable",
                "laudable", "mellow", "noble", "observant",
                "practical", "quizzing", "resourceful", "steadfast",
                "tactful", "upbeat", "vibrant", "witty",
                "zealot"};
        } else if (lenguaje.equalsIgnoreCase("Español")) {
            String[] palabrasEspañol = {"abrazo", "aceite", "amigo", "anillo", "arbusto", "arbol", "arena", "aroma", "arte", "avenida",
                "azul", "bailar", "barco", "beso", "bicicleta", "blanco", "boca", "bolsa", "botella", "brillante",
                "cabello", "cama", "caminar", "cancion", "carro", "carta", "casa", "celeste", "cerca", "cielo",
                "ciudad", "color", "comida", "conectar", "correr", "crecer", "crema", "cruzar", "cuerpo", "danza",
                "dia", "dibujo", "diente", "divertido", "dormir", "eco", "efecto", "elastico", "enamorado", "energia",
                "escalera", "espacio", "espejo", "familia", "flor", "frio", "fuego", "gato", "globo", "grande",
                "hoja", "hombre", "idea", "imagen", "jardin", "juego", "leche", "luz", "maleta", "mar",
                "mesa", "montana", "musica", "nadar", "nieve", "noche", "nube", "numero", "oso", "pajaro",
                "palabra", "pantalon", "papel", "parque", "pasion", "pato", "pelo", "perro", "pescado", "pluma",
                "puerta", "rio", "rojo", "saludar", "secreto", "silla", "sonido", "sueno", "taza", "television",
                "tierra", "tiempo", "tormenta", "trabajo", "universo", "verano", "verde", "vestido", "viento", "volar",
                "zanahoria", "zapato", "aguila", "ambar", "amigo", "ambar", "anfora", "animo", "ebano", "exito", "eter",
                "etnico", "agil", "agua", "epoca", "oleo", "opera", "optimo", "ovalo", "oxido", "unico", "inconstitucionalidad", "perpendicularidad", "esdrujula", "anticonstitucionalmente",
                "transubstanciacion", "prestidigitador", "ininteligibilidad", "gubernamentalmente",
                "electroencefalografia", "paleontologico", "autorretrato", "sobrealimentacion",
                "desoxirribonucleico", "desobstruccionismo", "eclesiasticamente", "descentralizacion",
                "paradigmatologico", "desproporcionadamente", "contrarrevolucionario", "paralelepipedo",
                "monosilabico", "aerodinamicamente", "ultramicroscopio", "autotransportable",
                "psicoanaliticamente", "arqueoastronomia", "desesperanzadoramente", "discrecionalidad",
                "hipopotomonstrosesquipedaliofobia", "encefalograma", "contrainteligencia", "hipopotamo",
                "hidroelectrolitico", "neuropsiquiatria", "reumatologico", "trascendentalismo",
                "macroeconomicamente", "autorregulacion", "paleontologo", "desarraigamiento",
                "transiluminacion", "fotodisociacion", "antisubversivo", "otorrinolaringologo",
                "hipocondriaco", "desfibrilador", "polarizacion", "desencadenante",
                "esternocleidomastoideo", "lexicograficamente", "hipermercado", "policromatico",
                "biotecnologico", "oftalmologico", "desmembramiento", "bucodental",
                "concientizadamente", "acantilado", "circunstancialmente", "colaboracionismo",
                "espectroscopio", "electrodomestico", "sociolinguistica", "subdirector",
                "desprestigio", "esternocleidomastoideitis", "geopoliticamente", "heterosexualidad",
                "infundadamente", "interpretativamente", "intelectualizacion", "microrred",
                "desestabilizacion", "perfeccionamiento", "policondritis", "semiotica",
                "oftalmopatia", "aracnofobia", "procrastinacion", "desestresante",
                "determinacion", "discriminacion", "efectivamente", "desfavorablemente",
                "expectativas", "frustracion", "generosamente", "habitualmente",
                "independientemente", "justificacion", "karma", "lamentablemente",
                "manipulacion", "necesariamente", "obstinadamente", "patologicamente",
                "querencia", "responsabilidad", "satisfactoriamente", "tumultuosamente",
                "ultrasonografia", "vulnerabilidad", "xenofobia", "yuxtaposicion",
                "zoogeografia", "absurdo", "benevolencia", "consecuencia", "delicado",
                "elogiante", "formidable", "gracioso", "hipotesis",
                "imparcial", "juicioso", "conocimiento", "luminoso",
                "meticuloso", "nutrir", "objetivo", "prevalente",
                "quemar", "resiliente", "sofisticado", "transparente",
                "ultimo", "vibrante", "vagar", "zelo",
                "adecuado", "brisk", "coherente", "diligente",
                "eclectico", "florecer", "genuino", "armonico",
                "iluminar", "jovial", "entusiasta", "lucido",
                "magnificar", "matiz", "optimista", "profundo",
                "pintoresco", "racional", "sereno", "tangible",
                "unificar", "versatil", "ingenioso", "celoso",
                "acumen", "valentia", "transmitir", "destreza",
                "eloquencia", "fortaleza", "gratitud", "humilde",
                "innovador", "juicio", "amabilidad", "animado",
                "modesto", "destacable", "optimismo", "apasionado",
                "curioso", "confiable", "sincero", "tenaz",
                "union", "vivido", "maravilloso", "juvenil",
                "entusiasmo", "afable", "felicidad", "compostura",
                "diligencia", "efervescente", "flexible", "gentil",
                "honestidad", "perspicaz", "alegre", "conocedor",
                "alabable", "sosegado", "noble", "observador",
                "practico", "curiosidad", "ingenioso", "firme",
                "diplomatico", "optimista", "vibrante", "oportuno",
                "valiente", "entusiasta", "comunicativo", "cooperativo",
                "paciente", "sociable", "colaborativo", "creativo"};
        }
    }

    public String getNextWord() {
        return palabras[(int) (Math.random() * palabras.length)];
    }
}
